---
-
  - fuck
  - fucks
  - fucker
  - fucking
  - motherfucker
  - motherfuckers
  - motherfucking
  - fucktastic
  - fuck-head
  - fucktard
  - fuckface
-
  - shit
  - shits
  - shitty
  - shiteater
  - shitstorm
  - shit-head
  - dipshit
-
  - ass
  - asses
  - asshole
  - assholes
  - jackass
  - jackasses
-
  - retard
  - retards
  - retarded
-
  - fag
  - fags
  - faggot
  - faggots
  - faggy
-
  - gay
  - gaylord
  - gaylords
  - fudgepacker
  - fudgepackers
-
  - nigger
  - niggers
  - nigga
  - niggas
  - niggra
  - niggras
-
  - chinaman
  - chinamen
  - chink
  - chinks
-
  - jap
  - japs
  - nip
  - nips
-
  - cracker
  - crackers
  - honky
  - honkies
  - peckerwood
  - peckerwoods
-
  - cock
  - cocks
  - cocksucker
  - cocksuckers
  - cockbite
  - dick
  - dicks
  - dickwad
  - dickwads
  - dickhead
  - dickheads
  - penis
-
  - cunt
  - vagina
  - muff
  - muffdiver
-
  - slut
  - sluts
  - skank
  - skanks
  - whore
  - whores
  - manwhore
  - manwhores
-
  - wanker
  - wankers
  - wank
-
  - bitch
  - bitches
  - bitchy
-
  - bastard
  - bastards
-
  - dyke
  - dykes
  - carpetmuncher
  - carpetmunchers
  - lesbo
  - lesbos