---
- fuck
- fucks
- fucker
- fucking
- fuck
- motherfucker
- fucktastic
- fuck-head
- fucktard

- shit
- shits
- shitty
- shittier
- shittiest
- shiteater
- shitstorm
- shit-head

- ass
- asses
- asshole
- assholes
- jackass
- jackasses

- retard
- retards
- retarded

- fag
- fags
- faggot
- faggots
- faggy
- gay
- gaylord
